### ISSUE TITLE
sapper-example

### ISSUE THREAD

**Issue by VadimVBond** [kalaspuffar/sapper-example#1]
notes

500
Unexpected end of JSON input

SyntaxError: Unexpected end of JSON input
    at http://localhost:3000/client/2193a74c524180fda760/notes.notes.js:316:46
    at async http://localhost:3000/client/2193a74c524180fda760/main.js:2341:8
    at async Promise.all (index 0)
    at async hydrate_target (http://localhost:3000/client/2193a74c524180fda760/main.js:2320:12)
    at async navigate (http://localhost:3000/client/2193a74c524180fda760/main.js:2193:38)

**Comment by kalaspuffar** [comment]
Hi @Vvbadim 

Interesting issue. Can you give me some more context so I'll be able to reproduce the issue easier?

Best regards
Daniel

**Comment by kalaspuffar** [comment]
John Hines wrote on youtube:
```
Very Cool, Thank you! I did notice when cloning the GitHub projects I noticed the db.json was empty but when I added the below JSON the Notes portion of the application started working correctly!
Add/update db.json to:

{
  "notes": [
    {
      "id": "99adafaswe1-asdf3-adsfa-adsf-adsfadfafa",
      "text": "Create a project!"
    },
    {
      "id": "98adafaswe1-asdf3-adsfa-adsf-adsfadfafa",
      "text": "Fixing bugs"
    },
    {
      "id": "97adafaswe1-asdf3-adsfa-adsf-adsfadfafa",
      "text": "Adding data"
    }
  ]
}
```

Maybe that could be the answer for you to?
